### ISSUE TITLE
! Failed to extract messages: entity not found !

### ISSUE THREAD

**Issue by kuncevic** [jeffcshelton/evaporate#3]
Just run the extraction, here is the result

```
Successfully extracted contacts.
! Failed to extract messages: entity not found !
Successfully extracted photos.
```

There are only two text files in `messages` folder, both threads extracted not if full.

Backup was downloaded from iCloud that created with from iphone 15

### Rust Versions:
cargo 1.71.1, rustup-init 1.26.0, rustup 1.26.0

p.s during compilation seeing a lot of depreciation messages related to src/messages.rs, may be this is a case?
```
warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
  --> src/messages.rs:69:20
   |
69 | ...   &NaiveDateTime::from_timestamp(row.get::<_, i64>(2)? + TIMESTAMP_O...
   |                       ^^^^^^^^^^^^^^

warning: use of deprecated method `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
  --> src/messages.rs:98:34
   |
98 |         let mut last_timestamp = Local.timestamp(0, 0);
```

and `src/contacts.rs` show warnings as well

```
warning: use of deprecated struct `chrono::Date`: Use `NaiveDate` or `DateTime<Tz>` instead
 --> src/contacts.rs:4:2
  |
4 |     Date,
  |     ^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `chrono::Date`: Use `NaiveDate` or `DateTime<Tz>` instead
  --> src/contacts.rs:40:24
   |
40 |     pub birthday: Option<(Date<Local>, bool)>,
   |                           ^^^^

warning: use of deprecated struct `chrono::Date`: Use `NaiveDate` or `DateTime<Tz>` instead
  --> src/contacts.rs:41:27
   |
41 |     pub anniversary: Option<(Date<Local>, bool)>,
   |                              ^^^^

warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
   --> src/contacts.rs:187:46
    |
187 | ...   (Local.from_utc_datetime(&NaiveDateTime::from_timestamp(timestamp...
    |                                                ^^^^^^^^^^^^^^

warning: use of deprecated method `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
   --> src/contacts.rs:187:76
    |
187 | ...::from_timestamp(timestamp, 0)).date(), include_year)
    |                                    ^^^^

warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
   --> src/contacts.rs:200:46
    |
200 | ...   (Local.from_utc_datetime(&NaiveDateTime::from_timestamp(timestamp...
    |                                                ^^^^^^^^^^^^^^

warning: use of deprecated method `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
   --> src/contacts.rs:200:76
    |
200 | ...::from_timestamp(timestamp, 0)).date(), include_year)
```

**Comment by jeffcshelton** [comment]
That's interesting... I'll be sure to fix the warnings but that's not what's causing the extraction to fail.

I suspect that Apple changed the path or format of the messages in the most recent version of iOS. I'll make an iOS 17 backup today and see if I can find the issue.

**Comment by kuncevic** [comment]
@jeffcshelton Oh, that would be great if you were able to test out that one. However, it's interesting that it was capable of extracting some portions of two threads.... I'm looking forward to hearing about your findings

**Comment by jeffcshelton** [comment]
I've been trying to replicate this bug, but I haven't been successful on my machine. Could you provide a few more details about your setup? Do you have any contacts that could be problematic as file names?

I will create a branch to fix the warnings and provide some `dbg!` statements that will help figure out what the underlying issue is.

**Comment by kuncevic** [comment]
@jeffcshelton oh I c. Yeah this sounds great I am happy to debug to figure out the error message.

update: this is the one https://github.com/jeffcshelton/evaporate/tree/issue/3-failed-extraction right?

**Comment by kuncevic** [comment]
Just installed the new version from the issue branch, run the extraction, got the same error `! Failed to extract messages: entity not found !` however now `messages` folder totally empty. Speaking about contacts having weird names, yes, I do have some contains emojis 🤔

**Comment by kuncevic** [comment]
Just installed the new version from the issue branch, run the extraction, got the same error ! Failed to extract messages: entity not found ! however now messages folder totally empty. 

Speaking about contacts having weird names, yes, I do have some contains emojis 🤔. Besides that running on mac, rust versions listed above in the original issue...

update: run for the second time, got other 2 threads, different to what I had originally, both cut. Then run again, got 1 thread for totally different contact.... All partially extracted threads does not have weird contact names

**Comment by jeffcshelton** [comment]
Ok thanks, I'll try adding some emojis in my backup and extracting to see if that's the issue. It would be strange if that is the problem though, as emojis are allowed in file names. The branch you mentioned is the correct one, but I hadn't yet pushed the commit with the debug statements.

Now I've pushed the debug statements, so try pulling the most recent changes on the issue branch and running again. Reply with the debug lines printed before the extraction fails. It should be the details of the contacts' names, extraction paths, and number of messages. If you are not comfortable with listing the actual names, then feel free to obfuscate them but leave any special characters, repetitions, and other patterns intact.

**Comment by kuncevic** [comment]
Hey @jeffcshelton  The debug messages was quite helpful, actually this seems not an emoji issue but forward slash.... I've run the extraction a couple of times and this is always hangs on any contact with forward slash in the name:

```
[src/messages.rs:101] &name = "X & Y / 2/3 appartment"
[src/messages.rs:102] &export_path = "00048131-00054C2001F80N1E_extract/messages/X & Y / 2/3 appartment.txt"
[src/messages.rs:103] conversation.len() = 54
```

or

```
[src/messages.rs:101] &name = "XYZ - / 123 / ABC - BLA"
[src/messages.rs:102] &export_path = "00048131-00054C2001F800N1E_extract/messages/XYZ - / 123 / ABC - BLA.txt"
[src/messages.rs:103] conversation.len() = 15
```

So, this is usually the last thing you see in the console. However, it does not get extracted into the destination because '/' is not allowed in filenames. I think it would be better to replace that with something like a pipe '|'. What do you think?

**Comment by jeffcshelton** [comment]
I agree. That should be what's causing the issue. The pipe character '|' is allowed in macOS file names, but in the future evaporate may also support Windows, which does not allow '|' in file names. To make it consistent, I'll have it replace all invalid characters with a dash '-'.

I will actually make a few modifications to the way evaporate handles file names:
1. Invalid characters (depending on the file system / OS) will be replaced with a dash ('-').
2. Directory traversal specifiers such as `.` and `..`, as well as empty names, will be replaced with "Unknown".
3. Repeated first + last names for contacts will be enumerated, starting at 1 for the first repeated name.

That way, hopefully no more issues will arise with invalid file paths. If you can think of any cases not covered by these changes, then I'd be happy to fix those too.

Thanks for bringing this issue to my attention. I hope this patch will enable you to extract everything without further issues. Look out for the pull request that will be associated with this issue and please confirm that it fixes the problem before I merge it.

**Comment by jeffcshelton** [comment]
Does this fix the issue?

**Comment by kuncevic** [comment]
Yeah I can confirm messages extraction works now, thank you for fixing the issue!
```
Successfully extracted contacts.
Successfully extracted messages.
Successfully extracted photos.
```
